---
title: "R Notebook"
---

```{r}
library(tidyverse)
library(here)
library(tidygraph)
library(ggraph)

theme_manuscript <- function() {
    theme(text = element_text(size = 8, family = 'Arial'), 
          aspect.ratio = 1,
          legend.box.margin = margin(t = 2, r = 2, b = 2, l = 2),
          legend.box.spacing = unit(2,'pt'), 
          legend.key.size = unit(10, 'pt'), 
          legend.title = element_text(size = 9),
          plot.title = element_text(size = 9, hjust = 0.5), 
          strip.text = element_text(size = 8),
          legend.text = element_text(size = 8))
}
```

```{r}
interaction_zscores <- read_csv(here('data', 'processed', 'gene_residuals.csv'))
```

```{r}
interaction_zscores_9_pairs <- interaction_zscores %>%
  filter(guide_pairs == 9)
```


```{r}
cutoff <- 1e-3
signif_combos <- interaction_zscores_9_pairs %>% 
  filter(condition %in% c('MOLM13_21', 'NOMO-1_21'), fdr_bh < cutoff) %>%
  mutate(condition = fct_recode(condition, MOLM13 = 'MOLM13_21', NOMO1 = 'NOMO-1_21'))
combo_graph <- signif_combos %>% select(gene_a, gene_b, pair_z_score, fdr_bh,
    condition) %>% as_tbl_graph()
score <- 'pair_z_score'
ggraph(combo_graph, layout = "stress", bbox = 3) + 
  geom_edge_link(aes(color = !!as.name(score), 
                             width = abs(!!as.name(score)))) + 
  scale_edge_width(range = c(0.5, 1.5)) + 
  geom_node_point(size=3, color='grey25', pch=21, fill='white') +
  geom_node_text(aes(label = name), size = 2.2,
                          repel = T, point.padding = 0, 
                          min.segment.length = 0.1, box.padding = 0.1) + 
  theme_void() + 
  theme_manuscript() +
  theme(panel.spacing = unit(0.4, 'cm')) + 
  scale_edge_color_gradient2() + 
  guides(edge_width = FALSE, 
         edge_colour = guide_edge_colourbar(title = 'Z-score', barwidth = 0.5)) +
  facet_edges("condition") +
  labs(title = paste('Interactions at FDR <', cutoff))
ggsave(here('figures', 'network_comparison.svg'), width = 12, height = 6, units = 'cm')
```

```{r}
cutoff <- 5
score <- 'combo_z_score'
signif_combos <- combo_scores %>% filter(abs(!!as.name(score)) > 
        cutoff, geneA != geneB)
combo_graph <- signif_combos %>% select(geneA, geneB, combo_z_score, 
    context) %>% tidygraph::as_tbl_graph()
ggraph::ggraph(combo_graph, layout = "stress", bbox = 3) + 
  ggraph::geom_edge_link(aes(color = !!as.name(score), 
                             width = abs(!!as.name(score)))) + 
  ggraph::scale_edge_width(range = c(1, 2.5)) + 
  ggraph::geom_node_label(aes(label = name), size = 2.83,
                          repel = T, point.padding = 0, label.padding = 0.1, 
                          min.segment.length = 0.1, box.padding = 0.1) + 
  theme_void() + 
  theme_manuscript() +
  theme(panel.spacing = unit(0.4, 'cm')) + 
  ggraph::scale_edge_color_gradient2() + 
  guides(edge_width = FALSE, 
         edge_colour = ggraph::guide_edge_colourbar(title = 'Z-score', barwidth = 0.5)) +
  ggraph::facet_edges("context")
ggsave(here('figures', 'apop', 'network.svg'), width = 10, height = 6, 
       units = 'cm')
```

```{r}
data_p <- plot_combo('MARCH5', 'WSB2', lfcs)
data_p$p +
  theme_minimal() +
  theme_manuscript() +
  theme(legend.position = 'top',
        axis.text.x = element_blank()) +
  ylab('Avg. LFC') +
  guides(color = guide_legend(nrow = 2)) +
  scale_color_manual(values = c('black','#66c2a5', '#fc8d62', '#8da0cb'))
ggsave(here('figures', 'apop', 'MARCH5_WSB2.svg'), width = 9, height = 5.5, units = 'cm')
```

```{r}
apop_avg_lfcs <- intactr::average_gene_scores(lfcs, 10)
combo_level_lfcs <- apop_avg_lfcs %>%
  select(-gene_lfcA, -gene_lfcB) %>%
  pivot_wider(names_from = 'context', values_from = 'avg_lfc')
cor.test(combo_level_lfcs$A375,
         combo_level_lfcs$OVCAR8)
```

```{r}
cor.test(spread_scores$A375, spread_scores$OVCAR8)
```

